#!/usr/bin/env python3
"""The ledger: the durable record of what was decided about each element.

Reading it, writing it, rendering it as Markdown, and the four verbs that
change it -- decide, describe, supersede, and the zeroing a superseded loser
gets. This is the deep module the directory's CONTEXT.md names; the seam is
that no caller may touch decisions.json except through here.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from harness_core import (AGENT_MAX_STARS, DECISION_STATES, HarnessError,
                          KEEP_BOOKMARK, KEEP_SENTIMENT, SENTIMENTS, SOURCES,
                          STAR_RANGE, VERSION, ZERO_STARS, write_json)


def empty_decisions() -> dict[str, object]:
    return {"version": VERSION, "state": "draft", "elements": [], "supersededCount": 0}


def load_decisions(output: Path) -> dict[str, object]:
    path = output / "decisions.json"
    if not path.is_file():
        raise HarnessError("decisions.json is missing; run `init` or re-bootstrap")
    return json.loads(path.read_text(encoding="utf-8"))


def render_decisions_md(decisions: dict[str, object]) -> str:
    live = [e for e in decisions["elements"] if e["state"] in ("approved", "proposed")]
    # `completed` is a status, not a lock, so it gets its own section rather than
    # sitting under Standing -- but it must still be rendered. Omitting it made
    # finished elements invisible to any agent resuming from this file.
    done = [e for e in decisions["elements"] if e["state"] == "completed"]
    dead = [e for e in decisions["elements"] if e["state"] in ("superseded", "rejected")]
    lines = [
        "# Design Decisions",
        "",
        "Generated by `bootstrap_harness.py decide`. Do not hand-edit.",
        "",
        "**Binding for any agent resuming this project.** An element listed under",
        "Standing may not be replaced, restyled, or dropped without an explicit",
        "`decide --supersedes` recorded here first. Chat history is not a record.",
        "",
        f"Lifecycle state: `{decisions['state']}`",
        "",
        "## Standing",
        "",
    ]
    if live:
        lines += ["| Element | Verdict | Stars | Evidence |", "| --- | --- | --- | --- |"]
        for e in sorted(live, key=lambda x: (-x["stars"], x["element"])):
            stars = "★" * e["stars"] + "☆" * (STAR_RANGE[1] - e["stars"])
            lines.append(f"| `{e['element']}` | {e['state']} | {stars} | {e['evidence']} |")
    else:
        lines.append("_No decisions recorded yet._")
    if done:
        lines += ["", "## Completed", "",
                  "Finished for now. Still binding as a record; iteration may continue.",
                  "", "| Element | Stars | Evidence |", "| --- | --- | --- |"]
        for e in sorted(done, key=lambda x: (-x["stars"], x["element"])):
            stars = "★" * e["stars"] + "☆" * (STAR_RANGE[1] - e["stars"])
            lines.append(f"| `{e['element']}` | {stars} | {e['evidence']} |")
    if dead:
        lines += ["", "## Superseded", ""]
        for e in sorted(dead, key=lambda x: x["element"]):
            note = f" → `{e['supersededBy']}`" if e.get("supersededBy") else ""
            lines.append(f"- ~~`{e['element']}`~~ ({e['state']}){note} — {e['evidence']}")
    return "\n".join(lines) + "\n"


def record_decision(project_root: Path, element: str, verdict: str, stars: int,
                    evidence: str, supersedes: list[str],
                    preview: dict[str, str] | None = None,
                    source: str = "agent",
                    sentiment: str | None | object = KEEP_SENTIMENT,
                    implemented: str | None = None,
                    description: str | None = None,
                    title: str | None = None,
                    scored: bool | None = None,
                    bookmarked: bool | object = KEEP_BOOKMARK) -> dict[str, object]:
    output = project_root.resolve(strict=True) / "spec" / "design-harness"
    if verdict not in DECISION_STATES:
        raise HarnessError(f"verdict must be one of: {', '.join(DECISION_STATES)}")
    if sentiment is not KEEP_SENTIMENT and sentiment is not None and sentiment not in SENTIMENTS:
        raise HarnessError(f"sentiment must be one of: {', '.join(SENTIMENTS)}, or None to withdraw it")
    if stars != ZERO_STARS and not STAR_RANGE[0] <= stars <= STAR_RANGE[1]:
        raise HarnessError(f"stars must be {STAR_RANGE[0]}-{STAR_RANGE[1]}, "
                           f"or {ZERO_STARS} meaning bad execution")
    if not evidence.strip():
        raise HarnessError("evidence is required: quote the user, do not paraphrase")
    if source not in SOURCES:
        raise HarnessError(f"source must be one of: {', '.join(SOURCES)}")
    if source == "agent" and stars > AGENT_MAX_STARS:
        raise HarnessError(
            f"agent-set rank is capped at {AGENT_MAX_STARS} star. A higher rank must come from a "
            "user click, adopted with `adopt` -- typing the number yourself is the failure this "
            "cap exists to prevent.")
    if source == "agent":
        stars = ZERO_STARS
    rank_was_set = source == "user" if scored is None else bool(scored)
    if source == "agent":
        rank_was_set = False
    decisions = load_decisions(output)
    known = {e["element"] for e in decisions["elements"]}
    missing = [s for s in supersedes if s not in known]
    if missing:
        raise HarnessError(f"cannot supersede unknown element(s): {', '.join(missing)}")
    for e in decisions["elements"]:
        if e["element"] in supersedes:
            e["state"] = "superseded"
            e["supersededBy"] = element
            decisions["supersededCount"] += 1
        elif e["element"] == element:
            e["state"], e["stars"], e["evidence"] = verdict, stars, evidence
            e["source"] = source
            # `scored` means THE USER ranked it. An agent placeholder is a
            # starting position, not a judgement -- recording it as scored
            # painted a gold star on every brand-new proposal, suppressed
            # the "sin puntuar" marker, and made a round the user had not
            # looked at yet read as one they had already judged badly.
            e["scored"] = rank_was_set
            if implemented is not None:
                e["implemented"] = implemented
            if description is not None:
                e["description"] = description
            if title is not None:
                e["title"] = title
            e.setdefault("implemented", None)
            e.setdefault("description", None)
            if sentiment is not KEEP_SENTIMENT:
                e["sentiment"] = sentiment
            e.setdefault("sentiment", None)
            if bookmarked is not KEEP_BOOKMARK:
                e["bookmarked"] = bool(bookmarked)
            e.setdefault("bookmarked", False)
            if preview is not None:
                e["preview"] = preview
            e.setdefault("preview", None)
            e.setdefault("tokens", None)
            break
    else:
        decisions["elements"].append({
            "element": element, "state": verdict, "stars": stars,
            "evidence": evidence, "supersededBy": None, "preview": preview,
            # Same rule on the create path as on the update path: an agent
            # placeholder is a starting position, never a score.
            "source": source, "scored": rank_was_set,
            "sentiment": None if sentiment is KEEP_SENTIMENT else sentiment, "tokens": None,
            "implemented": implemented, "description": description, "title": title,
            "bookmarked": False if bookmarked is KEEP_BOOKMARK else bool(bookmarked),
        })
    if any(e["state"] == "approved" for e in decisions["elements"]):
        decisions["state"] = "approved"
    elif decisions["state"] == "draft":
        decisions["state"] = "proposed"
    write_json(output / "decisions.json", decisions)
    (output / "DECISIONS.md").write_text(render_decisions_md(decisions), encoding="utf-8")
    project_path = output / "project.json"
    project = json.loads(project_path.read_text(encoding="utf-8"))
    project["state"] = decisions["state"]
    write_json(project_path, project)
    return decisions


def parse_tokens(raw: str) -> dict[str, object]:
    """The specimen data a design-system section is made of.

    A "Typography" heading over a scoring row is a list, not a design system:
    the section has to show the faces that were chosen, and a palette section
    has to show the actual colours. The ledger held ids and prose and no hex
    value anywhere, so that section could never be more than a list. Shape:

        {"colors": [{"name": "crema", "value": "#F4E9D2", "role": "paper"}],
         "fonts":  [{"name": "Söhne Mono", "stack": "ui-monospace",
                     "use": "display", "sample": "Aa"}]}
    """
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as err:
        raise HarnessError(f"--tokens is not valid JSON: {err}") from err
    return validate_tokens(value)


def validate_tokens(value: object) -> dict[str, object]:
    """Checked here, not in the CLI: the rules protect the ledger, so they have
    to hold for every caller rather than only for people typing a command."""
    if not isinstance(value, dict):
        raise HarnessError('--tokens must be a JSON object, e.g. {"colors": [...]}')
    for key, items in value.items():
        if key not in ("colors", "fonts"):
            raise HarnessError(f"unknown token group: {key} (expected colors or fonts)")
        if not isinstance(items, list) or not all(isinstance(i, dict) for i in items):
            raise HarnessError(f"{key} must be a list of objects")
    for swatch in value.get("colors", []):
        if not str(swatch.get("value", "")).strip():
            raise HarnessError("every colour token needs a `value` (the hex the design uses)")
    # Either every colour in a set is separately rankable or none is. A set
    # where only the first carries an `element` renders one swatch with a
    # star strip and the rest without -- which reads as a broken page, and
    # is how a three-colour palette came to show scoring under `amarillo`
    # alone. Half-linked is not a state the ledger should be able to hold.
    linked = [bool(str(c.get("element", "")).strip()) for c in value.get("colors", [])]
    if len(linked) > 1 and any(linked) and not all(linked):
        named = [str(c.get("name") or c.get("value"))
                 for c, has in zip(value.get("colors", []), linked) if not has]
        raise HarnessError(
            "these colours carry no `element`, but others in the same set do: "
            + ", ".join(named)
            + ". Give every colour its own element id so each is rankable, or give none of "
            "them one so the set is ranked by its own row. A set where only some are "
            "rankable renders as a palette that half failed to draw.")
    for face in value.get("fonts", []):
        if not str(face.get("name", "")).strip():
            raise HarnessError("every font token needs a `name` (the face that was chosen)")
        for key_name in ("element",):
            if face.get(key_name) is not None and not str(face[key_name]).strip():
                raise HarnessError(f"font `{key_name}` cannot be blank")
        variants = face.get("variants")
        if variants is not None:
            if not isinstance(variants, list) or not all(isinstance(v, dict) for v in variants):
                raise HarnessError("font `variants` must be a list of objects")
            for variant in variants:
                if not str(variant.get("use", "")).strip():
                    raise HarnessError(
                        "every font variant needs a `use` -- a weight nobody can point at a job "
                        "is a specimen, not a system")
    return value


def describe_element(project_root: Path, element: str,
                     description: str | None, implemented: str | None,
                     tokens: dict[str, object] | None = None) -> dict[str, object]:
    """Label an existing element without touching its verdict, rank or source.

    `decide` cannot do this: it demands a verdict and a rank, so relabelling a
    user-ranked row means retyping the user's stars -- the invention the star cap
    exists to prevent.
    """
    output = project_root.resolve(strict=True) / "spec" / "design-harness"
    if description is None and implemented is None and tokens is None:
        raise HarnessError("nothing to set: pass --description, --implemented and/or --tokens")
    decisions = load_decisions(output)
    for entry in decisions["elements"]:
        if entry["element"] == element:
            break
    else:
        raise HarnessError(f"unknown element: {element}. Record it with `decide` first.")
    if description is not None:
        entry["description"] = description
    if implemented is not None:
        entry["implemented"] = implemented
    if tokens is not None:
        entry["tokens"] = validate_tokens(tokens)
    write_json(output / "decisions.json", decisions)
    (output / "DECISIONS.md").write_text(render_decisions_md(decisions), encoding="utf-8")
    return entry


def retire_element(project_root: Path, loser: str, winner: str,
                   evidence: str) -> dict[str, object]:
    """Retire `loser` in favour of `winner`, touching nothing on the winner.

    `decide --supersedes` cannot do this. It records the supersede on the
    WINNER, and the winner is necessarily the element the user just ranked --
    so writing it re-runs the agent path, which is capped at 1 star and stamps
    `source=agent`. Recording a win therefore destroyed the very click that
    decided it: a user's 3-star rank came back as agent 1-star, and `adopt`
    would not restore it because it had already consumed that click. The
    supersede belongs on the loser, where nothing the user set is at stake.
    """
    output = project_root.resolve(strict=True) / "spec" / "design-harness"
    if loser == winner:
        raise HarnessError("an element cannot supersede itself")
    if not evidence.strip():
        raise HarnessError("evidence is required: quote the user, do not paraphrase")
    decisions = load_decisions(output)
    by_id = {e["element"]: e for e in decisions["elements"]}
    for name in (loser, winner):
        if name not in by_id:
            raise HarnessError(f"unknown element: {name}. Record it with `decide` first.")
    entry = by_id[loser]
    if entry["state"] == "superseded" and entry.get("supersededBy") == winner:
        return entry
    entry["state"] = "superseded"
    entry["supersededBy"] = winner
    entry["evidence"] = evidence
    decisions["supersededCount"] += 1
    if any(e["state"] == "approved" for e in decisions["elements"]):
        decisions["state"] = "approved"
    write_json(output / "decisions.json", decisions)
    (output / "DECISIONS.md").write_text(render_decisions_md(decisions), encoding="utf-8")
    project_path = output / "project.json"
    project = json.loads(project_path.read_text(encoding="utf-8"))
    project["state"] = decisions["state"]
    write_json(project_path, project)
    return entry


def display_name(entry: dict[str, object]) -> str:
    """What to call this design in front of a designer.

    The card used to be headed `cover.object.character-drawn.dentro-de-margen.
    sin-colision`. That is a stable id for the ledger and it is unreadable as a
    title -- the reader has to parse a namespace to find out what they are
    looking at. A plain `--title` wins; failing that the id's last meaningful
    segment is humanised, which at least reads as words.
    """
    given = str(entry.get("title") or "").strip()
    if given:
        return given
    # No title set: the description already says what this is, in the user's
    # own language, so its first clause beats a humanised id every time --
    # "el objeto de portada dibujado grande" against "Sin colision".
    described = str(entry.get("description") or "").strip()
    if described:
        clause = re.split(r"[,;:.\u2014]| -- ", described, maxsplit=1)[0].strip()
        if 3 <= len(clause) <= 64:
            return clause[0].upper() + clause[1:]
    parts = [part for part in str(entry["element"]).split(".") if part]
    tail = " ".join(parts[-2:]) if len(parts) > 2 else " ".join(parts)
    tail = tail.replace("-", " ").replace("_", " ").replace(".", " ").strip()
    return (tail[0].upper() + tail[1:]) if tail else str(entry["element"])


def display_names(entries: list[dict[str, object]]) -> dict[str, str]:
    """Names for a whole list, guaranteed distinct.

    A redraw inherits its parent's description, so `cover.object.character-drawn`
    and `...dentro-de-margen.sin-colision` both resolved to "El objeto de portada
    dibujado grande" -- and the round view puts exactly those two side by side as
    before and after. Two identical titles over two different drawings is worse
    than the dotted id was. Collisions take the segment that distinguishes them.
    """
    names: dict[str, str] = {}
    taken: dict[str, str] = {}
    for entry in entries:
        element = str(entry["element"])
        name = display_name(entry)
        if name in taken and taken[name] != element:
            tail = element.split(".")[-1].replace("-", " ").replace("_", " ")
            name = f"{name} — {tail}"
        taken.setdefault(name, element)
        names[element] = name
    return names


def score_zero(project_root: Path, element: str) -> None:
    """Score an element zero: the worst rating, deliberately given.

    This is a judgement, not an erasure -- `scored` stays true. A zero says the
    execution is bad; it says nothing about whether the element should exist,
    so state is left exactly where it was.
    """
    output = project_root.resolve(strict=True) / "spec" / "design-harness"
    decisions = load_decisions(output)
    for entry in decisions["elements"]:
        if entry["element"] == element:
            # Encouragement and completion are separate signals with their
            # own controls; a zero touches the execution score only.
            entry["stars"] = ZERO_STARS
            entry["scored"] = True
            break
    write_json(output / "decisions.json", decisions)
    (output / "DECISIONS.md").write_text(render_decisions_md(decisions), encoding="utf-8")


def ledger_stats(decisions: dict[str, object]) -> dict[str, object]:
    """Deterministic aggregates over the ledger. Same ledger, same numbers.

    The headline is `coverage`: what fraction of standing elements carry a
    signal the user actually set. A high star average means nothing if the
    agent typed all of it.
    """
    elements = decisions["elements"]
    live = [e for e in elements if e["state"] in ("approved", "proposed")]
    user = [e for e in live if e.get("source") == "user" and e.get("scored")]
    ranked = sorted((e["stars"] for e in user))

    def median(values: list[int]) -> float:
        if not values:
            return 0.0
        mid = len(values) // 2
        return float(values[mid]) if len(values) % 2 else (values[mid - 1] + values[mid]) / 2

    histogram = {str(n): sum(1 for e in user if e["stars"] == n)
                 for n in range(STAR_RANGE[0], STAR_RANGE[1] + 1)}
    # A user who liked something but scored it low, or disliked something still
    # standing, is telling you something an average would hide.
    # Good idea, not yet beautiful: improve the drawing, never drop it.
    needs_polish = sorted(e["element"] for e in live
                          if e.get("sentiment") == "like" and e["stars"] <= 2)
    # Well drawn but the direction is discouraged: that is the real contradiction.
    conflicts = sorted(e["element"] for e in live
                       if e.get("sentiment") == "dislike" and e["stars"] >= 4)
    return {
        "standing": len(live),
        "userSet": len(user),
        "agentSet": len(live) - len(user),
        "coverage": round(len(user) / len(live), 3) if live else 0.0,
        "meanStars": round(sum(ranked) / len(ranked), 2) if ranked else 0.0,
        "medianStars": median(ranked),
        "histogram": histogram,
        "likes": sum(1 for e in live if e.get("sentiment") == "like"),
        "dislikes": sum(1 for e in live if e.get("sentiment") == "dislike"),
        "approved": sum(1 for e in elements if e["state"] == "approved"),
        "completed": sum(1 for e in elements if e["state"] == "completed"),
        "rejected": sum(1 for e in elements if e["state"] == "rejected"),
        "superseded": sum(1 for e in elements if e["state"] == "superseded"),
        "unscored": sorted(e["element"] for e in live if not e.get("scored")),
        "conflicts": conflicts, "needsPolish": needs_polish,
    }
